theme: minima
title: '💑 Maggie and Buro got married! Come celebrate!'
author:
  name:  '\0/ Buro and Maggie <3'
timezone: UTC−07:00
logo: /assets/favicon.png
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
header_pages: ['']
