theme: minima
title: |
  💑 Come Celebrate Maggie and Buro's Marriage!
author:
  name:  '\0/ Buro and Maggie <3'
timezone: UTC−07:00
logo: /assets/favicon.png
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
